FROM golang:alpine AS builder

WORKDIR /go/src/app
COPY main.go .

RUN go mod init github.com/Bombaninha/fc-mod1-des1
RUN go build -ldflags="-s -w" -o /go/bin/app


FROM scratch
COPY --from=builder /go/bin/app /app
ENTRYPOINT ["/app"]
